### ISSUE TITLE
What does "if user hasn't tapped on the frame or any embedded frame yet." Mean?

### ISSUE THREAD

**Issue by Andalusio** [apache/cordova-plugin-vibration#117]
This issue is with Android, and not even Google Gemini could help figure out how to get navigate.vibrate to work by adding "touchend" via "addEventListener." I feel like this will never be available on Android, and I needed this for a gimmick in one of my games.

And what is this "frame" the readme speaks of?

**Comment by Andalusio** [comment]
Never mind. With help from Google Gemini, I figured a way of just using tapping on the screen in general to trigger vibration. In case you're interested, here is an example:

`var isUserInteracted = false; // Flag to track user interaction

document.addEventListener("touchstart", function() {
    isUserInteracted = true; // Set flag upon user interaction
});

var intervalId = null; // Variable to store the interval ID

function checkAndVibrate() {
    if (isUserInteracted) {
        navigator.vibrate(kickTime);
    }
}

function startInterval() {
    if (!intervalId) { // Start the interval only if not already running
        intervalId = setInterval(checkAndVibrate, 1); // Interval duration is 1 millisecond
    }
}

function stopInterval() {
    if (intervalId) {
        clearInterval(intervalId);
        intervalId = null;
    }
}

// Start the interval after user interaction
chatbodyObj.addEventListener("touchstart", startInterval);

// Stop the interval when necessary (e.g., on game exit)
// ...`

Maybe something like this should be included into the readme under the Android section? Again, it took Google Gemini to know a work-around to the restrictions.

**Comment by Andalusio** [comment]
Of course, the above code examples are ideal for working with intervals, which was what I was looking for for an in-game gimmick I had in mind.

**Comment by jcesarmobile** [comment]
You don't really need any of that code, you can still call vibrate even before the user touched the screen, it will just not vibrate and will return false
