### ISSUE TITLE
 navigator.vibrate() Does not work in IOS 12.2

### ISSUE THREAD

**Issue by rijink7** [apache/cordova-plugin-vibration#84]
# Bug Report
There is no error shown
## Problem
 navigator.vibrate() Does not work in IOS 12.2
### What is expected to happen?
the phone should vibrate

### What does actually happen?
the phoneDoes not vibrate

### Command or Code

 navigator.vibrate()

### Environment, Platform, Device

Cordova IOS 5.0.1
cordova-plugin-vibration 3.1.0 "Vibration"

### Version information

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.4.1, (and 23 other plugins)

System:

   Android SDK Tools : 26.0.2 (/Users/afscdev/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.1
   NodeJS            : v11.8.0 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS
   Xcode             : Xcode 10.2.1 Build version 10E1001

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by djipco** [comment]
I cannot make this work in iOS 12.3.1 either (packaged with Phonegap).

**Comment by djipco** [comment]
> I cannot make this work in iOS 12.3.1 either (packaged with Phonegap).

When I upgraded to 3.1.1, it fixed the problem for me.

**Comment by jcesarmobile** [comment]
I can't reproduce. Make sure you are passing a time, `navigator.vibrate()` doesn't work, but `navigator.vibrate(1000)` works, as documented.
