### ISSUE TITLE
Vibration not working on iPhone 11 

### ISSUE THREAD

**Issue by fedrod** [apache/cordova-plugin-vibration#87]
# Bug Report
No vibration on iPhone 11 Pro, iOS 13.3.1
## Problem
navigator.vibrate does not vibrate phone
### What is expected to happen?

App should vibrate when function called

### What does actually happen?

App does not vibrate

## Information
navigator.vibrate(200) as well as navigator.vibrate([200]) on iPhone 11 Pro, iOS 13.3.1 has no effect.

### Command or Code

navigator.vibrate(200) as well as navigator.vibrate([200]) on iPhone 11 Pro, iOS 13.3.1 has no effect.

### Environment, Platform, Device

iPhone 11 Pro, iOS 13.3.1
 

### Version information

9.0.0 (cordova-lib@9.0.1)
<engine name="ios" version="^5.0.0" />

## Checklist

- [x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by timbru31** [comment]
Unable to reproduce (tested on an iPhone 6 with iOS 12.4.6 and an iPhone 7 with 13.4). Please provide a reproducible example as asked.
